# Comportamiento del Consumidor {#U2}
La presente unidad ayudará a los estudiantes a comprender las decisiones económicas tomadas por los consumidores de alimentos y productos agrícolas. Los temas incluyen las fuerzas que influyen en el comportamiento del consumidor (Sección 3); el concepto de demanda de mercado para un producto en particular (Sección 4); y la elasticidad de la demanda (Sección 5). La especificación de medidas clave de elasticidad se complementa con ejemplos empíricos y su relevancia para la toma de decisiones en la industria de alimentos y fibras, incluida la magnitud potencial de la respuesta del consumidor y su implicancia en los ingresos del productor.

## Sección 3: Teoría del comportamiento del consumidor {.unnumbered #Sec3}

 El proceso biológico de la fotosíntesis, en el que la adición de luz al entorno de una planta da como resultado el crecimiento de esta, se puede considerar en un contexto de estímulo-respuesta. El estímulo es la adición de luz, y la respuesta es el crecimiento de la planta. Este proceso se puede estudiar en un entorno controlado utilizando sofisticados dispositivos de medición.

El comportamiento económico también se puede pensar en un contexto de estímulo-respuesta. Por ejemplo, una caída en el precio del helado actúa como un estímulo, provocando que los consumidores compren más helado. Estas compras se pueden medir y registrar.

En la mayoría de los aspectos, sin embargo, las similitudes terminan aquí. El complejo proceso de la fotosíntesis puede examinarse y estudiarse directamente, pero la mayoría de los procesos de comportamiento económico no pueden estudiarse de esta manera. De hecho, este ejemplo ilustra la distinción entre las ciencias naturales (por ejemplo, biología, química, física) y las ciencias sociales (por ejemplo, economía). La mayoría de los procesos de comportamiento económico no se pueden estudiar en un entorno controlado.

Podemos examinar las relaciones técnicas de conversión de insumos a productos en un proceso de producción, pero no podemos observar el proceso de conectar el estímulo económico con una decisión económica. ¿Por qué Juan compra más helado que Sofía cuando ambos enfrentan los mismos precios y tienen los mismos ingresos?

Las teorías económicas más prominentes sobre el comportamiento del consumidor asumen que los consumidores son racionales y buscan maximizar su satisfacción sin salirse de su presupuesto. En esta sección, discutimos la teoría del consumidor y cómo se puede utilizar para comprender el comportamiento de los consumidores. 

## Sección 4: Equilibrio del Consumidor y Demanda del Mercado {.unnumbered #Sec4}

## Sección 5: Medidas e interpretación de elasticidades {.unnumbered #Sec5}
Here is a review of existing methods.
